# Generated by Django 3.0.3 on 2020-07-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.IntegerField()),
                ('year2', models.IntegerField()),
                ('revenue1', models.IntegerField()),
                ('revenue2', models.IntegerField()),
                ('operations1', models.IntegerField()),
                ('operations2', models.IntegerField()),
                ('profitTax1', models.IntegerField()),
                ('profitTax2', models.IntegerField()),
                ('tax1', models.IntegerField()),
                ('tax2', models.IntegerField()),
                ('profit1', models.IntegerField()),
                ('profit2', models.IntegerField()),
            ],
        ),
    ]
