# Generated by Django 3.0.3 on 2020-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_incomestatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,  default='1990-01-01'),
            preserve_default=False,
        ),
    ]
