# Generated by Django 3.0.3 on 2020-07-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0007_auto_20200713_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
