# Generated by Django 3.0.3 on 2020-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0008_remove_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowStatemement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.CharField(max_length=20, null=True)),
                ('year2', models.CharField(max_length=20, null=True)),
                ('cashOperations1', models.CharField(max_length=20, null=True)),
                ('cashInvesting1', models.CharField(max_length=20, null=True)),
                ('cashInvesting2', models.CharField(max_length=20, null=True)),
                ('cashFinancing1', models.CharField(max_length=20, null=True)),
                ('cashFinancing2', models.CharField(max_length=20, null=True)),
                ('netBalance1', models.CharField(max_length=20, null=True)),
                ('netBalance2', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionStatemement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.CharField(max_length=20, null=True)),
                ('year2', models.CharField(max_length=20, null=True)),
                ('totalFixed1', models.CharField(max_length=20, null=True)),
                ('totalFixed2', models.CharField(max_length=20, null=True)),
                ('totalCurrent1', models.CharField(max_length=20, null=True)),
                ('totalCurrent2', models.CharField(max_length=20, null=True)),
                ('totalAssets1', models.CharField(max_length=20, null=True)),
                ('totalAssets2', models.CharField(max_length=20, null=True)),
                ('equity1', models.CharField(max_length=20, null=True)),
                ('equity2', models.CharField(max_length=20, null=True)),
                ('totalLiab1', models.CharField(max_length=20, null=True)),
                ('totalLiab2', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
