# Generated by Django 3.0.3 on 2020-07-15 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_cashflowstatemement_positionstatemement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowstatemement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 15, 21, 7, 43, 724640, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='total1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='total2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
