# Generated by Django 3.0.3 on 2020-07-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_auto_20200715_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowstatemement',
            name='cashOperations2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
