# Generated by Django 3.0.3 on 2020-07-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_cashflowstatemement_cashoperations2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('value1', models.CharField(max_length=200, null=True)),
                ('value2', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
