# Generated by Django 3.0.3 on 2020-07-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0013_auto_20200726_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestatement',
            name='add_name1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='add_name2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='add_value1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='add_value2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='add_value3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='add_value4',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
