# Generated by Django 3.0.3 on 2020-07-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0015_auto_20200726_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowstatemement',
            name='addC_name1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatemement',
            name='addC_name2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatemement',
            name='addC_value1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatemement',
            name='addC_value2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatemement',
            name='addC_value3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatemement',
            name='addC_value4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='addB_name1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='addB_name2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='addB_value1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='addB_value2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='addB_value3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='positionstatemement',
            name='addB_value4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
