# Generated by Django 3.0.3 on 2020-07-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0016_auto_20200726_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowstatemement',
            name='addC_name1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowstatemement',
            name='addC_name2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='add_name1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='add_name2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='positionstatemement',
            name='addB_name1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='positionstatemement',
            name='addB_name2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
